### ISSUE TITLE
template-native-sdk.html not loading

### ISSUE THREAD

**Issue by sathishsr** [ChartIQ/Charting-Library---Android-Sample-App#2]
Hi,

I got the evaluation library from ChartIQ team and integrated in the sample. I can able to load template-advanced.html and template-basic.html. 
But template-native-sdk.html is not loading in the chartIQ view.

**Comment by jdrichards50** [comment]
Hello Sathishsr,

I'll be looking into your issue.  I have a couple questions.

1 - Which version of the ChartIQ library are you using?
2 - I'm assuming you are using Android Studio, so are there any errors in the Android Monitor?

thanks

**Comment by jdrichards50** [comment]
@sathishsr, were you able to fix your issue?

**Comment by sathishsr** [comment]
Hello, there is no errors on Android Monitor. setDataSource callbacks are not triggered when I start the initialization. Library version 3.0.8

**Comment by jdrichards50** [comment]
@sathishsr, I'll look into the issue and get back to you.

**Comment by jdrichards50** [comment]
@sathishsr, I've checked out a fresh copy of the Android sample app and downloaded a copy of the ChartIQ 3.0.8 library.  I'm having no issue loading template-native-sdk.html into the webview.  

Have you made any modifications to MainActivity.java?  If not, is it possible to send us your copy of the library we sent you.  I would want to check that out and see if anything is broken.  

Also, if you have the time, we can screenshare and see if we can diagnose the issue together.
